#!/usr/bin/env python3

import json
import argparse

description = '''
Compare the difference between two snapshots.
'''

parser = argparse.ArgumentParser(prog='DiffSnapshot', description=description)

parser.add_argument('oldfile', help='The path to the old snapshot file')
parser.add_argument('newfile', help='The path to the new snapshot file')

args = parser.parse_args()

with open(args.oldfile) as f:
    old = json.load(f)

with open(args.newfile) as f:
    new = json.load(f)

common_plugins = [i for i in old.keys() if i in new.keys()]
old_plugins = [i for i in old.keys() if i not in new.keys()]
new_plugins = [i for i in new.keys() if i not in old.keys()]

for plugin in common_plugins:
    if old[plugin]['commit'] != new[plugin]['commit']:
        print(plugin, old[plugin]['commit'], new[plugin]['commit'])

for plugin in old_plugins:
    print(plugin, old[plugin]['commit'])

for plugin in new_plugins:
    print(plugin, new[plugin]['commit'])
