#!/usr/bin/env python3

import json
import argparse

description = '''
Compare the difference between two snapshots.
'''

parser = argparse.ArgumentParser(prog='DiffSnapshot', description=description)

parser.add_argument('oldfile',
                    help='The path to the old snapshot file')
parser.add_argument('newfile',
                    help='The path to the new snapshot file')

args = parser.parse_args()

with open(args.oldfile) as f:
    old = json.load(f)

with open(args.newfile) as f:
    new = json.load(f)


for plugin in old.keys():
    if old[plugin]['commit'] != new[plugin]['commit']:
        print(plugin, old[plugin]['commit'], new[plugin]['commit'])
